version: 2
jobs:
  build:
    working_directory: ~/play2-maven-plugin/play2-maven-test-projects

    environment:
      _JAVA_OPTIONS: -Xms512m -Xmx1024m

    docker:
    - image: circleci/openjdk:8-jdk-stretch

    steps:
    - checkout
    - restore_cache:
        keys:
        # This branch if available
        - v1-dep-{{ .Branch }}-
        # Default branch if not
        - v1-dep-master-
        # Any branch if there are none on the default branch - this should be unnecessary if you have your default branch configured correctly
        - v1-dep-
    - run: java -XX:+PrintFlagsFinal -version
    - run: mvn --version
    - run: mvn verify --update-snapshots --settings .travis.settings.xml -e
    - save_cache:
        key: v1-dep-{{ .Branch }}-{{ epoch }}
        paths:
        - ~/.m2
        - ~/.ivy2/cache
        - ~/.sbt/boot
        - ~/.zinc
